C_Practice: include/linked_list.h File Reference
linked_list.h File Reference
Data Structures
struct Node_T
struct Du_Node_T
Typedefs
typedef struct Node_T Node
typedef struct Node_T * P_Node
typedef struct Du_Node_T Du_Node
typedef struct Du_Node_T * P_Du_Node
Functions
void linked_list_dynamic_init (P_Node *p_node)
void linked_list_push_node (P_Node *head_ref, int data)
void linked_list_reverse (P_Node *head_ref)
void printList (P_Node head)
void printList_middle (P_Node head_ref)
Typedef Documentation
Du_Node
typedef struct Du_Node_T Du_Node
Dummy Doubly Linked list
Node
typedef struct Node_T Node
Dummy Linked list
P_Du_Node
typedef struct Du_Node_T * P_Du_Node
P_Node
typedef struct Node_T * P_Node
Function Documentation
linked_list_dynamic_init()
void linked_list_dynamic_init (P_Node * p_node)
This function is allocating the dynamic memory to the node...
Parameters
Pass a pointer-to-lined-list. it can change the memory address stored at that memory location.
Returns
none
 {
     * p_node = (P_Node)malloc(sizeof(Node));
 }
Referenced by main().
linked_list_push_node()
void linked_list_push_node (P_Node * head_ref, int data)
This function is pushing a new node at the front...
Parameters
Pass a pointer-to-struct. it can change the memory address stored at that memory location.
Assign data to a new node.
Returns
none
 {
     P_Node init_node = (P_Node)malloc(sizeof(Node));
     init_node->data = data;
     init_node->next = (struct Node*) (* head_ref);
     (* head_ref) = init_node;
 }
Referenced by main().
linked_list_reverse()
void linked_list_reverse (P_Node * head_ref)
This function is reversing the linked list... Reverse function (Input: 1->2->3->4->NULL; Output: 4->3->2->1->NULL)
Initialize three pointers: prev (NULL), curr (head), next (NULL).
Iterate trough the linked list.
next = curr->next // store next node
curr->next = prev // actual reserving happens
One step forward
prev = curr
curr = next
Parameters
Pass a pointer-to-lined-list. it can change the memory address stored at that memory location.
Returns
none
 {
     P_Node prev = NULL;
     P_Node curr = * head_ref;
     P_Node next = NULL;
     while (curr != NULL) {
         // store next node
         next = (P_Node) curr->next;
         // reverse
         curr->next = (struct Node *) prev;
         // One step forward
         prev = curr;
         curr = next;
     }
     *head_ref = prev;
 }
Referenced by main().
printList()
void printList (P_Node head)
This function is printing contents of linked list starting from the given node...
Parameters
Starting node.
Returns
none
 {
     P_Node temp = head;
     // Protect
     while(temp != NULL)
     {
         printf("%d  ", temp->data);
         temp = (P_Node) temp->next;
     }
     printf("\n");
 }
Referenced by main().
printList_middle()
void printList_middle (P_Node head_ref)
This function is printing middle of linked list...
Parameters
Starting node.
Returns
none
 {
     P_Node p_fast_node = head_ref;
     P_Node p_slow_node = head_ref;
     if(head_ref != NULL) {
         while (p_fast_node != NULL && p_fast_node->next != NULL) {
             p_fast_node = (P_Node) p_fast_node->next;
             p_fast_node = (P_Node) p_fast_node->next;
             p_slow_node = (P_Node) p_slow_node->next;
         }
         printf("The meddle elements is: %d \n", p_slow_node->data);
     }
 }
Referenced by main().